/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/pokemon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista de Pokémon
         * @description Todas las formas cargadas, en orden de la Pokédex Nacional, con sus tipos actuales y si
         *     están en favoritos. Las formas regionales son entradas propias.
         */
        get: operations["list_pokemon_api_pokemon_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pokemon/{pokemon}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ficha de un Pokémon
         * @description Número, nombre, tipos actuales, línea evolutiva completa y el mecanismo de cada
         *     evolución. `404` si la forma no existe.
         */
        get: operations["pokemon_detail_api_pokemon__pokemon__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pokemon/{pokemon}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Imagen de un Pokémon
         * @description La imagen de la forma (su *sprite* de PokeAPI, recortado a la figura), que la carga de
         *     datos guarda en la caché local. Es la URL que dan las respuestas en `image_url`. `404` si
         *     la forma no existe o no tiene imagen.
         */
        get: operations["pokemon_image_api_pokemon__pokemon__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pokemon/{pokemon}/artwork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ilustración de un Pokémon
         * @description La ilustración oficial de la forma, de hasta 256 px, para la ficha. La carga de datos la
         *     guarda en la caché local. Es la URL que da la ficha en `artwork_url`. `404` si la forma no
         *     existe o no tiene ilustración.
         */
        get: operations["pokemon_artwork_api_pokemon__pokemon__artwork_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista de favoritos
         * @description Los favoritos, en orden de la Pokédex Nacional, y cuántos hay.
         */
        get: operations["list_favorites_api_favorites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/{pokemon}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Añadir un favorito
         * @description Añade la forma `pokemon`, la evolución hasta la que se quiere llegar (RN-09). Si ya era
         *     favorito, no cambia nada. `404` si la forma no existe en los datos cargados.
         */
        put: operations["add_favorite_api_favorites__pokemon__put"];
        post?: never;
        /**
         * Quitar un favorito
         * @description Quita `pokemon` de favoritos. `404` si no estaba.
         */
        delete: operations["remove_favorite_api_favorites__pokemon__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo de reglas
         * @description Las 20 reglas del catálogo, en orden, con su tipo, si son configurables, si están
         *     activas y su peso.
         */
        get: operations["list_rules_api_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Activar, desactivar o cambiar el peso de una regla
         * @description Cambia `enabled`, `weight` (de 0 a 10, solo en las blandas) o los dos. `404` si la regla
         *     no existe; `409` si no es configurable o no es blanda y se le da peso; `422` si el peso está
         *     fuera de rango o no se indica nada.
         */
        patch: operations["update_rule_api_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Juegos objetivo
         * @description Los juegos que se pueden elegir como objetivo, en orden de lanzamiento: los juegos
         *     completos, que permiten la crianza y tienen todos los datos que necesitan las reglas, y que
         *     no están ya registrados en el *Hall of Fame* (RF-05, CA-68). Con `all=true`, todos los
         *     juegos cargados; `target` dice cuáles pueden ser juego objetivo y `completed`, cuáles ya
         *     están registrados.
         */
        get: operations["list_games_api_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portada de un juego
         * @description La portada del juego, de hasta 256 px, que la carga de datos descarga de WikiDex y guarda
         *     en la caché local (ADR-0011). Vale para cualquier juego cargado, también los que no son
         *     juego objetivo. Es la URL que dan las respuestas en `cover_url`. `404` si el juego no está
         *     cargado o no tiene portada.
         */
        get: operations["game_cover_api_games__game__cover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Datos sin verificar del juego
         * @description Los datos inferidos o pendientes que intervienen en la generación con los favoritos y
         *     las reglas actuales, con su propuesta y su estado (RN-18). Con `pending` a 0 se puede
         *     generar. `404` si el juego no es juego objetivo; `409` si ya está registrado en el *Hall of
         *     Fame* (CA-68).
         */
        get: operations["get_review_api_games__game__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game}/review/{fact_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Confirmar o corregir un dato
         * @description Confirma el dato con el valor propuesto o con uno corregido: un booleano o, en un
         *     combate clave, la lista de Pokémon de su equipo. `404` si el dato no existe en el juego;
         *     `409` si se cargó sin ambigüedad (automático) o si el juego ya está registrado en el *Hall
         *     of Fame* (CA-68); `422` si el valor no es del tipo del dato o
         *     el equipo incluye Pokémon que no existen en la generación del juego.
         */
        put: operations["confirm_api_games__game__review__fact_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game}/review/accept-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aceptar todas las propuestas
         * @description Confirma de una vez todas las propuestas inferidas que intervienen y aún no están
         *     confirmadas. Los datos pendientes, sin propuesta, se confirman uno a uno. Devuelve la
         *     revisión actualizada. `409` si el juego ya está registrado en el *Hall of Fame* (CA-68).
         */
        post: operations["accept_proposals_api_games__game__review_accept_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game}/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generar equipos
         * @description Genera los equipos con los favoritos, las reglas y las confirmaciones actuales. No se
         *     guarda: es un cálculo. `409` con los datos pendientes si queda alguno sin confirmar, o con
         *     el registro del *Hall of Fame* si el juego ya está registrado (CA-68); `404` si el juego no
         *     es juego objetivo.
         */
        post: operations["generate_api_games__game__generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game}/team-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Comprobar un equipo elegido
         * @description Comprueba el equipo elegido en el resultado (favoritos y sugerencias) con las reglas
         *     activas: que cada miembro pase los filtros (RN-03, RN-11, RN-16), que no haya dos
         *     incompatibles (RN-07, RN-12, RN-14, RN-21) y que se cumplan las reglas de presencia
         *     (RN-13, RN-14, RN-21). No se guarda. `409` si quedan datos sin confirmar, como al generar,
         *     o si el juego ya está registrado en el *Hall of Fame* (CA-68); `422` si un
         *     miembro se repite o no existe en la generación del juego; `404` si el juego no es juego
         *     objetivo.
         */
        post: operations["check_team_api_games__game__team_checks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hall-of-fame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recorrido
         * @description Los registros en el orden del recorrido: por fecha y, a igualdad, por orden de registro.
         *     `last` marca el último juego completado. Con `game`, solo los de ese juego.
         */
        get: operations["list_entries_api_hall_of_fame_get"];
        put?: never;
        /**
         * Registrar un equipo
         * @description Registra el equipo con el que se completó un juego. Guarda los tipos que tenía cada
         *     miembro en ese juego. `409` si el juego ya está registrado: cada juego se registra una
         *     sola vez (CA-68). `422` si el juego o algún Pokémon no existen en los datos cargados (o en
         *     la generación del juego).
         */
        post: operations["add_entry_api_hall_of_fame_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hall-of-fame/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eliminar un registro
         * @description Elimina el registro, su equipo y la Pokédex del juego (CA-68). `404` si no existe.
         */
        delete: operations["remove_entry_api_hall_of_fame__entry_id__delete"];
        options?: never;
        head?: never;
        /**
         * Corregir un registro
         * @description Cambia el juego, la fecha, las notas o el equipo. Si cambia el juego o el equipo, se
         *     vuelven a copiar los tipos; si cambia el juego, se borra la Pokédex del anterior (CA-68).
         *     `404` si el registro no existe; `409` si el juego nuevo ya está registrado; `422` como al
         *     registrarlo.
         */
        patch: operations["update_entry_api_hall_of_fame__entry_id__patch"];
        trace?: never;
    };
    "/api/pokedex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pokédex de los juegos superados
         * @description Los juegos registrados en el *Hall of Fame*, en el orden del recorrido, con el progreso
         *     de su Pokédex (RF-20, RN-22). Los juegos que ya no están cargados no aparecen.
         */
        get: operations["list_pokedexes_api_pokedex_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pokedex/{game}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pokédex de un juego
         * @description Todos los Pokémon de la Pokédex del juego, en su orden, con lo que ha marcado el usuario:
         *     la lista inicial (RF-21) y el detalle de registrados e imposibles (RF-24). `404` si el
         *     juego no está en el *Hall of Fame*.
         */
        get: operations["get_pokedex_api_pokedex__game__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pokedex/{game}/initial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Confirmar la lista inicial
         * @description Guarda los Pokémon que el usuario ya tiene registrados y empieza la Pokédex (RF-21).
         *     Solo una vez: después se corrige con cada Pokémon. `404` si el juego no está en el *Hall of
         *     Fame*; `409` si ya estaba confirmada; `422` si alguna especie no está en la Pokédex.
         */
        put: operations["start_pokedex_api_pokedex__game__initial_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pokedex/{game}/objective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pokémon objetivo
         * @description La ficha del primer Pokémon de la Pokédex que no está registrado, ni es imposible, ni se
         *     ha saltado (RN-23, RF-22), con todas sus formas de obtención. Nula si no queda ninguno.
         *     `404` si el juego no está en el *Hall of Fame*.
         */
        get: operations["get_objective_api_pokedex__game__objective_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pokedex/{game}/pokemon/{species}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ficha de un Pokémon
         * @description El Pokémon con todas sus formas de obtención, de la más sencilla a la menos, la
         *     recomendada y la elegida por el usuario marcadas (RF-22, RF-23, RN-24 a RN-26). `404` si
         *     el juego no está en el *Hall of Fame* o la especie no está en su Pokédex.
         */
        get: operations["get_pokemon_api_pokedex__game__pokemon__species__get"];
        /**
         * Marcar un Pokémon
         * @description Lo registra, lo marca como imposible o lo desmarca (`status`), y elige su forma de
         *     obtención (`chosen_method`). Solo cambian los campos indicados (RF-22 a RF-24). `404` como
         *     en la ficha; `409` si no se ha confirmado la lista inicial; `422` si la forma no es suya.
         */
        put: operations["mark_pokemon_api_pokedex__game__pokemon__species__put"];
        post?: never;
        /**
         * Desmarcar un Pokémon
         * @description Quita su marca y la forma elegida, para corregir un error (RF-24). `404` como en la
         *     ficha; `409` si no se ha confirmado la lista inicial.
         */
        delete: operations["unmark_pokemon_api_pokedex__game__pokemon__species__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versión de la aplicación y de los datos
         * @description Versión de la aplicación y de la carga de datos con la que trabaja (commit de PokeAPI,
         *     fecha y juegos). `503` si todavía no se han cargado los datos o hay que repetir la carga.
         */
        get: operations["get_meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CatalogOut */
        CatalogOut: {
            /**
             * Total
             * @description Pokémon que cumplen los filtros.
             */
            total: number;
            /**
             * Pokemon
             * @description En orden de la Pokédex Nacional.
             */
            pokemon: components["schemas"]["CatalogPokemonOut"][];
        };
        /** CatalogPokemonOut */
        CatalogPokemonOut: {
            /**
             * Pokemon
             * @description Identificador de la forma, p. ej. `vulpix-alola`.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español; el de una forma regional la identifica.
             */
            name: string;
            /**
             * Dex Number
             * @description Número de la Pokédex Nacional.
             */
            dex_number: number;
            /**
             * Types
             * @description Tipos actuales (de la última generación cargada).
             */
            types: string[];
            /**
             * Region
             * @description Región de una forma regional (`alola`, `galar`…).
             */
            region: string | null;
            /**
             * Favorite
             * @description Si está en favoritos.
             */
            favorite: boolean;
            /**
             * Image Url
             * @description URL de su imagen en esta API (`/api/pokemon/{pokemon}/image`); nula si la forma no tiene imagen.
             */
            image_url: string | null;
        };
        /** CompletedGameDetail */
        CompletedGameDetail: {
            /**
             * Message
             * @description Explicación en español.
             */
            message: string;
            /**
             * Hall Of Fame Entry
             * @description El registro del *Hall of Fame* de ese juego.
             */
            hall_of_fame_entry: number;
        };
        /**
         * CompletedGameOut
         * @description Body of the 409 when the game is already recorded in the Hall of Fame (CA-68).
         */
        CompletedGameOut: {
            /** @description El mensaje y el registro del *Hall of Fame* que ya tiene el juego. */
            detail: components["schemas"]["CompletedGameDetail"];
        };
        ConditionValue: string | number | boolean;
        /** ConfirmationIn */
        ConfirmationIn: {
            /** @description El valor propuesto o corregido. Un booleano (mecánica, existencia o llegada) o, en un combate clave, la lista de Pokémon de su equipo en orden. */
            value: components["schemas"]["ReviewValue"];
        };
        /** ConfirmedFactOut */
        ConfirmedFactOut: {
            /**
             * Fact Key
             * @description Clave estable del dato confirmado.
             */
            fact_key: string;
            /** @description Tipo de dato, como en la revisión. */
            kind: components["schemas"]["FactKind"];
            /**
             * Name
             * @description Nombre en español de la mecánica, el entrenador o el Pokémon.
             */
            name: string;
            /** @description Valor confirmado: un booleano o, en un combate clave, la lista de su equipo. */
            value: components["schemas"]["ReviewValue"];
        };
        /**
         * DataVersion
         * @description The load that built reference.sqlite.
         */
        DataVersion: {
            /**
             * Pokeapi Commit
             * @description Commit del volcado de PokeAPI usado.
             */
            pokeapi_commit: string | null;
            /**
             * Sprites Commit
             * @description Commit del repositorio de imágenes de PokeAPI usado; nulo si la carga no incluye imágenes.
             */
            sprites_commit: string | null;
            /**
             * Ingested At
             * Format: date-time
             * @description Cuándo terminó la carga.
             */
            ingested_at: string;
            /**
             * Games
             * @description Juegos cargados.
             */
            games: string[];
        };
        /** DexEvolutionOut */
        DexEvolutionOut: {
            /**
             * Trigger
             * @description Disparador de PokeAPI (`level-up`, `use-item`, `trade`…).
             */
            trigger: string;
            /**
             * Conditions
             * @description Condiciones de PokeAPI (`minimum_level`, `trigger_item`…).
             */
            conditions: {
                [key: string]: string | number | boolean;
            };
        };
        /**
         * DexStatus
         * @description How the user marked a species in a Pokédex (RF-21, RF-22).
         * @enum {string}
         */
        DexStatus: "registered" | "impossible";
        /** DiscardOut */
        DiscardOut: {
            /**
             * Pokemon
             * @description Identificador del favorito descartado.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /**
             * Rule Id
             * @description Regla que lo descarta.
             */
            rule_id: string;
            /** @description `generation`, `game` o `arrival` (RN-03), `breeding` (RN-11) o `journey` (RN-16). */
            reason: components["schemas"]["DiscardReason"];
            /**
             * Detail
             * @description Explicación en español.
             */
            detail: string;
            /**
             * Fact Key
             * @description El dato confirmado por el usuario que decidió el descarte, si lo hay.
             */
            fact_key: string | null;
        };
        /**
         * DiscardReason
         * @enum {string}
         */
        DiscardReason: "generation" | "game" | "arrival" | "breeding" | "journey";
        /**
         * EncounterKind
         * @description Kinds of RN-26 in their order, then the two that RN-24 puts almost last.
         * @enum {string}
         */
        EncounterKind: "gift" | "npc_trade" | "fossil" | "static" | "wild" | "swarm" | "roaming" | "starter_gift" | "event";
        /** EvolutionMethodOut */
        EvolutionMethodOut: {
            /**
             * Trigger
             * @description Disparador de PokeAPI: `level-up`, `use-item`, `trade`, `shed`…
             */
            trigger: string;
            /**
             * Conditions
             * @description Condiciones de PokeAPI, p. ej. `{"minimum_level": 16}` o `{"trigger_item": "thunder-stone"}`.
             */
            conditions: {
                [key: string]: components["schemas"]["ConditionValue"];
            };
        };
        /** EvolutionOut */
        EvolutionOut: {
            /**
             * From Pokemon
             * @description Forma que evoluciona.
             */
            from_pokemon: string;
            /**
             * To Pokemon
             * @description Forma a la que evoluciona.
             */
            to_pokemon: string;
            /**
             * Version Group
             * @description Grupo de versiones más reciente con datos de esta evolución.
             */
            version_group: string;
            /**
             * Methods
             * @description Formas de evolucionar; varias si hay métodos alternativos.
             */
            methods: components["schemas"]["EvolutionMethodOut"][];
        };
        /**
         * FactKind
         * @enum {string}
         */
        FactKind: "mechanic" | "key_battle" | "exists" | "arrival";
        /** FavoriteOut */
        FavoriteOut: {
            /**
             * Pokemon
             * @description Identificador de la forma, p. ej. `vulpix-alola`.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /**
             * Dex Number
             * @description Número de la Pokédex Nacional.
             */
            dex_number: number;
            /**
             * Types
             * @description Tipos actuales (de la última generación cargada).
             */
            types: string[];
            /**
             * Image Url
             * @description URL de su imagen en esta API (`/api/pokemon/{pokemon}/image`); nula si la forma no tiene imagen.
             */
            image_url: string | null;
            /**
             * Added At
             * Format: date-time
             * @description Cuándo se añadió a favoritos.
             */
            added_at: string;
        };
        /** FavoritesOut */
        FavoritesOut: {
            /**
             * Total
             * @description Número de favoritos.
             */
            total: number;
            /**
             * Favorites
             * @description En orden de la Pokédex Nacional.
             */
            favorites: components["schemas"]["FavoriteOut"][];
        };
        /** GameOut */
        GameOut: {
            /**
             * Game
             * @description Identificador del juego, p. ej. `firered`.
             */
            game: string;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /**
             * Generation
             * @description Generación del juego.
             */
            generation: number;
            /**
             * Version Group
             * @description Grupo de versiones, p. ej. `firered-leafgreen`.
             */
            version_group: string;
            /**
             * Target
             * @description Si se puede elegir como juego objetivo: es un juego completo y no está registrado en el *Hall of Fame* (RF-05).
             */
            target: boolean;
            /**
             * Completed
             * @description Si ya está registrado en el *Hall of Fame*. Cada juego se registra una sola vez (CA-68).
             */
            completed: boolean;
            /**
             * Cover Url
             * @description URL de su portada en esta API (`/api/games/{game}/cover`); nula si el juego no tiene portada (RF-18).
             */
            cover_url: string | null;
            /**
             * Cover Source Url
             * @description Página del fichero de la portada en WikiDex, su titular y procedencia (CA-56, ADR-0011); nula si el juego no tiene portada.
             */
            cover_source_url: string | null;
        };
        /** GenerationOut */
        GenerationOut: {
            /**
             * Game
             * @description Identificador del juego objetivo.
             */
            game: string;
            /** @description `complete` si hay equipos de 6 favoritos; si no, `incomplete` (RN-08). */
            status: components["schemas"]["GenerationStatus"];
            /** @description Si es incompleto: `reserved_slot` (una regla de presencia necesita un Pokémon que no es favorito), `not_enough_candidates` (menos de 6 válidos) o `no_valid_team` (no hay 6 que cumplan juntos las reglas). */
            incomplete_reason: components["schemas"]["IncompleteReason"] | null;
            /**
             * Score
             * @description Puntuación de los equipos recomendados, redondeada.
             */
            score: number;
            /**
             * Groups
             * @description Los equipos empatados en cabeza, ya desempatados con RN-19, agrupados.
             */
            groups: components["schemas"]["GroupOut"][];
            /**
             * Discards
             * @description Favoritos descartados, en orden de la Pokédex Nacional (RF-10).
             */
            discards: components["schemas"]["DiscardOut"][];
            /**
             * Presence
             * @description Las reglas de presencia activas.
             */
            presence: components["schemas"]["PresenceOut"][];
            /**
             * Confirmed Facts
             * @description Datos confirmados por el usuario que intervienen en la generación (RF-09).
             */
            confirmed_facts: components["schemas"]["ConfirmedFactOut"][];
            /** @description La carga de datos usada. */
            data_version: components["schemas"]["DataVersion"] | null;
        };
        /**
         * GenerationStatus
         * @enum {string}
         */
        GenerationStatus: "complete" | "incomplete";
        /**
         * GroupOut
         * @description Tied teams that only differ in interchangeable members (CA-33).
         */
        GroupOut: {
            /**
             * Positions
             * @description Por cada posición, los Pokémon que la pueden ocupar, todos con los mismos tipos. Cada combinación es uno de los equipos del grupo.
             */
            positions: components["schemas"]["PokemonOut"][][];
            /**
             * Teams
             * @description Cada combinación de las posiciones: un equipo del grupo.
             */
            teams: components["schemas"]["TeamOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HallOfFameEntryIn */
        HallOfFameEntryIn: {
            /**
             * Game
             * @description Juego completado: cualquiera de los cargados que no esté ya registrado (CA-68).
             */
            game: string;
            /**
             * Completed On
             * Format: date
             * @description Cuándo se completó.
             */
            completed_on: string;
            /**
             * Notes
             * @description Notas opcionales.
             */
            notes?: string | null;
            /**
             * Members
             * @description Las formas del equipo, de 1 a 6, en orden (`vulpix-alola` para Vulpix de Alola). Puede repetirse una forma.
             */
            members: string[];
        };
        /** HallOfFameEntryOut */
        HallOfFameEntryOut: {
            /**
             * Id
             * @description Identificador del registro.
             */
            id: number;
            /**
             * Game
             * @description Identificador del juego completado.
             */
            game: string;
            /**
             * Game Name
             * @description Nombre en español del juego.
             */
            game_name: string;
            /**
             * Generation
             * @description Generación del juego (la de su lanzamiento); nula si ya no está cargado.
             */
            generation: number | null;
            /**
             * Cover Url
             * @description URL de su portada en esta API (`/api/games/{game}/cover`); nula si el juego no tiene portada (RF-18).
             */
            cover_url: string | null;
            /**
             * Cover Source Url
             * @description Página del fichero de la portada en WikiDex, su titular y procedencia (CA-56, ADR-0011); nula si el juego no tiene portada.
             */
            cover_source_url: string | null;
            /**
             * Completed On
             * Format: date
             * @description Cuándo se completó el juego.
             */
            completed_on: string;
            /**
             * Notes
             * @description Notas del usuario; nulas si no tiene.
             */
            notes: string | null;
            /**
             * Order
             * @description Posición en el recorrido: por fecha y, a igualdad, por orden de registro.
             */
            order: number;
            /**
             * Last
             * @description Si es el último juego completado del recorrido.
             */
            last: boolean;
            /**
             * Members
             * @description El equipo, en orden.
             */
            members: components["schemas"]["HallOfFameMemberOut"][];
        };
        /** HallOfFameMemberOut */
        HallOfFameMemberOut: {
            /**
             * Position
             * @description Posición en el equipo, de 1 a 6.
             */
            position: number;
            /**
             * Pokemon
             * @description Identificador de la forma.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /**
             * Types
             * @description Tipos que tenía en ese juego, copiados al registrarlo.
             */
            types: string[];
            /**
             * Image Url
             * @description URL de su imagen en esta API (`/api/pokemon/{pokemon}/image`); nula si la forma no tiene imagen.
             */
            image_url: string | null;
        };
        /**
         * HallOfFamePatch
         * @description What to change; at least one field. ``notes: null`` removes the notes.
         */
        HallOfFamePatch: {
            /**
             * Game
             * @description Juego completado, si cambia.
             */
            game?: string | null;
            /**
             * Completed On
             * @description Fecha, si cambia.
             */
            completed_on?: string | null;
            /**
             * Notes
             * @description Notas; `null` las quita.
             */
            notes?: string | null;
            /**
             * Members
             * @description Las formas del equipo, de 1 a 6, en orden (`vulpix-alola` para Vulpix de Alola). Puede repetirse una forma.
             */
            members?: string[] | null;
        };
        /**
         * IncompleteReason
         * @description Why there is no team of 6 favourites (RN-08, RF-10).
         * @enum {string}
         */
        IncompleteReason: "reserved_slot" | "not_enough_candidates" | "no_valid_team";
        /** InitialListIn */
        InitialListIn: {
            /**
             * Registered
             * @description Las especies que el usuario ya tiene registradas; puede estar vacía (RF-21).
             */
            registered: string[];
        };
        /** LineMemberOut */
        LineMemberOut: {
            /**
             * Pokemon
             * @description Identificador de la forma, p. ej. `vulpix-alola`.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español; el de una forma regional la identifica.
             */
            name: string;
            /**
             * Dex Number
             * @description Número de la Pokédex Nacional.
             */
            dex_number: number;
            /**
             * Types
             * @description Tipos actuales (de la última generación cargada).
             */
            types: string[];
            /**
             * Region
             * @description Región de una forma regional (`alola`, `galar`…).
             */
            region: string | null;
            /**
             * Favorite
             * @description Si está en favoritos.
             */
            favorite: boolean;
            /**
             * Image Url
             * @description URL de su imagen en esta API (`/api/pokemon/{pokemon}/image`); nula si la forma no tiene imagen.
             */
            image_url: string | null;
            /**
             * Stage
             * @description Etapa en la línea: 1 para la primera.
             */
            stage: number;
        };
        /**
         * LoadedOrigin
         * @description Origin of a reviewable value in the load (RN-18); automatic ones are not reviewed.
         * @enum {string}
         */
        LoadedOrigin: "inferred" | "pending";
        /** Meta */
        Meta: {
            /**
             * App Version
             * @description Versión de la aplicación.
             */
            app_version: string;
            /** @description La carga de los datos; nula si no hay registro. */
            data: components["schemas"]["DataVersion"] | null;
        };
        /**
         * MethodKind
         * @description Forms of RN-24 in their order, after evolving the previous stage.
         * @enum {string}
         */
        MethodKind: "evolve" | "breed_registered" | "transfer_registered" | "in_game" | "breed" | "transfer" | "starter_gift" | "event";
        /** ObjectiveOut */
        ObjectiveOut: {
            /** @description La ficha del Pokémon objetivo; nula si no queda ninguno por registrar (RN-23, RF-22). */
            pokemon: components["schemas"]["PokedexPokemonOut"] | null;
        };
        /** ObtentionMethodOut */
        ObtentionMethodOut: {
            /**
             * Key
             * @description Identificador estable de la forma, para elegirla (RF-23).
             */
            key: string;
            /** @description `evolve`, `breed_registered` (1), `transfer_registered` (2), `in_game` (3), `breed` (4), `transfer` (5), `starter_gift` (6) o `event` (7), en el orden de RN-24. */
            kind: components["schemas"]["MethodKind"];
            /**
             * Recommended
             * @description Si es la más sencilla (RN-24).
             */
            recommended: boolean;
            /**
             * Chosen
             * @description Si es la que eligió el usuario (RF-23, CA-75).
             */
            chosen: boolean;
            /** @description Dónde se obtiene: en el juego, en un regalo que depende del inicial, en un evento con lugar o, al transferirlo de un juego no superado, allí. */
            way: components["schemas"]["WayOut"] | null;
            /**
             * Game
             * @description Juego desde el que se transfiere (RN-25).
             */
            game: string | null;
            /**
             * Game Name
             * @description Nombre en español de ese juego.
             */
            game_name: string | null;
            /**
             * Pokemon
             * @description Especie que se evoluciona o se cría.
             */
            pokemon: string | null;
            /**
             * Pokemon Name
             * @description Nombre en español de esa especie.
             */
            pokemon_name: string | null;
            /**
             * Pokemon Registered
             * @description Si esa especie está registrada; si no, la ficha enlaza a la suya (CA-76).
             */
            pokemon_registered: boolean;
            /** @description El paso de evolución, al evolucionarlo. */
            evolution: components["schemas"]["DexEvolutionOut"] | null;
            /**
             * Incense
             * @description Si criarlo exige que el progenitor lleve un incienso.
             */
            incense: boolean;
        };
        /** OpenSlotsOut */
        OpenSlotsOut: {
            /**
             * Count
             * @description Cuántos huecos son.
             */
            count: number;
            /**
             * Rule Id
             * @description La regla de presencia que reserva el hueco; nula si son huecos libres.
             */
            rule_id: string | null;
            /**
             * Suggestions
             * @description Todas las que encajan, de mejor a peor (CA-50). Con varios huecos libres, cada una encaja con el equipo, pero no necesariamente con las demás.
             */
            suggestions: components["schemas"]["SuggestionOut"][];
        };
        /** PendingDataDetail */
        PendingDataDetail: {
            /**
             * Message
             * @description Explicación en español.
             */
            message: string;
            /**
             * Pending
             * @description Los datos que faltan por confirmar.
             */
            pending: components["schemas"]["ReviewFactOut"][];
        };
        /**
         * PendingDataOut
         * @description Body of the 409 when some data that takes part is still unverified (RN-18).
         */
        PendingDataOut: {
            /** @description El mensaje y los datos que faltan por confirmar. */
            detail: components["schemas"]["PendingDataDetail"];
        };
        /** PokedexGameOut */
        PokedexGameOut: {
            /**
             * Game
             * @description Identificador del juego superado.
             */
            game: string;
            /**
             * Game Name
             * @description Nombre en español del juego.
             */
            game_name: string;
            /**
             * Cover Url
             * @description URL de su portada en esta API; nula si no tiene (RF-18).
             */
            cover_url: string | null;
            /**
             * Hall Of Fame Entry
             * @description El registro del *Hall of Fame* del juego.
             */
            hall_of_fame_entry: number;
            /** @description Progreso de su Pokédex (RN-22). */
            progress: components["schemas"]["PokedexProgressOut"];
        };
        /**
         * PokedexMarkIn
         * @description What to change; at least one field.
         */
        PokedexMarkIn: {
            /**
             * Status
             * @description `registered`, `impossible` o `null` para desmarcarlo (RF-22, RF-24).
             */
            status?: ("registered" | "impossible") | null;
            /**
             * Chosen Method
             * @description Clave de una de sus formas (`key`), o `null` para volver a la recomendada (RF-23).
             */
            chosen_method?: string | null;
        };
        /** PokedexOut */
        PokedexOut: {
            /**
             * Game
             * @description Identificador del juego superado.
             */
            game: string;
            /**
             * Game Name
             * @description Nombre en español del juego.
             */
            game_name: string;
            /**
             * Hall Of Fame Entry
             * @description El registro del *Hall of Fame* del juego.
             */
            hall_of_fame_entry: number;
            /** @description Progreso de la Pokédex (RN-22). */
            progress: components["schemas"]["PokedexProgressOut"];
            /**
             * Species
             * @description Todos los Pokémon de la Pokédex, en su orden (RF-21, RF-24).
             */
            species: components["schemas"]["PokedexSpeciesOut"][];
        };
        /** PokedexPokemonOut */
        PokedexPokemonOut: {
            /**
             * Species
             * @description Identificador de la especie: la Pokédex registra especies.
             */
            species: string;
            /**
             * Number
             * @description Número en la Pokédex del juego, que da su orden (RN-23).
             */
            number: number;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /**
             * Pokemon
             * @description Su forma base, la de su imagen y sus tipos.
             */
            pokemon: string;
            /**
             * Types
             * @description Tipos en la generación del juego (RN-10).
             */
            types: string[];
            /**
             * Image Url
             * @description URL de su imagen en esta API; nula si no tiene (RF-17).
             */
            image_url: string | null;
            /** @description `registered`, `impossible` (marcado por el usuario) o nulo si no está marcado (RF-21, RF-22). */
            status: components["schemas"]["DexStatus"] | null;
            /**
             * Automatically Impossible
             * @description Si solo se obtiene en spin-offs, sin ninguna otra forma (RN-25).
             */
            automatically_impossible: boolean;
            /**
             * Artwork Url
             * @description URL de su ilustración oficial en esta API; nula si no tiene.
             */
            artwork_url: string | null;
            /**
             * Chosen Method
             * @description Clave de la forma elegida por el usuario; nula si sigue la recomendada.
             */
            chosen_method: string | null;
            /**
             * Methods
             * @description Todas las formas de obtenerlo, de la más sencilla a la menos (RN-24); vacía si no se conoce ninguna.
             */
            methods: components["schemas"]["ObtentionMethodOut"][];
        };
        /** PokedexProgressOut */
        PokedexProgressOut: {
            /**
             * Registered
             * @description Pokémon registrados (capturados u obtenidos, CA-69).
             */
            registered: number;
            /**
             * Total
             * @description Pokémon de la Pokédex del juego (RN-22).
             */
            total: number;
            /**
             * Impossible
             * @description Pokémon sin registrar imposibles de obtener: los marcados por el usuario y los que solo se obtienen en spin-offs (RN-25). Cuentan en el total (CA-71).
             */
            impossible: number;
            /**
             * Percent
             * @description Porcentaje de registrados sobre el total, redondeado hacia abajo: 100 solo con la Pokédex completa (RN-22).
             */
            percent: number;
            /** @description `not_started` hasta confirmar la lista inicial (RF-21), `in_progress` o `completed` con todos registrados. */
            status: components["schemas"]["PokedexStatus"];
        };
        /** PokedexSpeciesOut */
        PokedexSpeciesOut: {
            /**
             * Species
             * @description Identificador de la especie: la Pokédex registra especies.
             */
            species: string;
            /**
             * Number
             * @description Número en la Pokédex del juego, que da su orden (RN-23).
             */
            number: number;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /**
             * Pokemon
             * @description Su forma base, la de su imagen y sus tipos.
             */
            pokemon: string;
            /**
             * Types
             * @description Tipos en la generación del juego (RN-10).
             */
            types: string[];
            /**
             * Image Url
             * @description URL de su imagen en esta API; nula si no tiene (RF-17).
             */
            image_url: string | null;
            /** @description `registered`, `impossible` (marcado por el usuario) o nulo si no está marcado (RF-21, RF-22). */
            status: components["schemas"]["DexStatus"] | null;
            /**
             * Automatically Impossible
             * @description Si solo se obtiene en spin-offs, sin ninguna otra forma (RN-25).
             */
            automatically_impossible: boolean;
        };
        /**
         * PokedexStatus
         * @description States of a Pokédex (RN-22).
         * @enum {string}
         */
        PokedexStatus: "not_started" | "in_progress" | "completed";
        /** PokemonDetailOut */
        PokemonDetailOut: {
            /**
             * Pokemon
             * @description Identificador de la forma, p. ej. `vulpix-alola`.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español; el de una forma regional la identifica.
             */
            name: string;
            /**
             * Dex Number
             * @description Número de la Pokédex Nacional.
             */
            dex_number: number;
            /**
             * Types
             * @description Tipos actuales (de la última generación cargada).
             */
            types: string[];
            /**
             * Region
             * @description Región de una forma regional (`alola`, `galar`…).
             */
            region: string | null;
            /**
             * Favorite
             * @description Si está en favoritos.
             */
            favorite: boolean;
            /**
             * Image Url
             * @description URL de su imagen en esta API (`/api/pokemon/{pokemon}/image`); nula si la forma no tiene imagen.
             */
            image_url: string | null;
            /**
             * Artwork Url
             * @description URL de su ilustración oficial, más grande, para la ficha (`/api/pokemon/{pokemon}/artwork`); nula si la forma no tiene.
             */
            artwork_url: string | null;
            /**
             * Generation
             * @description Generación en que apareció la especie.
             */
            generation: number;
            /**
             * Species
             * @description Especie de la forma: la misma para sus formas regionales.
             */
            species: string;
            /**
             * Is Legendary
             * @description Si la especie es legendaria.
             */
            is_legendary: boolean;
            /**
             * Is Mythical
             * @description Si la especie es singular.
             */
            is_mythical: boolean;
            /**
             * Line
             * @description La línea evolutiva completa, con todas sus formas, por etapa y número.
             */
            line: components["schemas"]["LineMemberOut"][];
            /**
             * Evolutions
             * @description Cada evolución de la línea y su mecanismo.
             */
            evolutions: components["schemas"]["EvolutionOut"][];
        };
        /** PokemonOut */
        PokemonOut: {
            /**
             * Pokemon
             * @description Identificador de la forma.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /**
             * Dex Number
             * @description Número de la Pokédex Nacional.
             */
            dex_number: number;
            /**
             * Types
             * @description Tipos en el juego objetivo, el primario primero.
             */
            types: string[];
            /**
             * Image Url
             * @description URL de su imagen en esta API (`/api/pokemon/{pokemon}/image`); nula si la forma no tiene imagen.
             */
            image_url: string | null;
        };
        /** PresenceOut */
        PresenceOut: {
            /**
             * Rule Id
             * @description Regla de presencia: `RN-13`, `RN-14` o `RN-21`.
             */
            rule_id: string;
            /**
             * Level
             * @description Nivel de la regla en el DDF que se aplica.
             */
            level: number;
            /** @description `candidates` (el equipo incluye una de `options`, que son favoritos), `chosen` (el equipo incluye una de `options`, que no son favoritos: solo RN-21), `reserved` (se reserva un hueco para una de `options`, que no son favoritos) o `unmet` (no se puede cumplir). */
            status: components["schemas"]["PresenceStatus"];
            /**
             * Options
             * @description Los Pokémon que la cumplen en ese nivel.
             */
            options: string[];
            /**
             * Detail
             * @description Explicación en español.
             */
            detail: string;
        };
        /**
         * PresenceStatus
         * @enum {string}
         */
        PresenceStatus: "candidates" | "chosen" | "reserved" | "unmet";
        /** ReviewFactOut */
        ReviewFactOut: {
            /**
             * Fact Key
             * @description Clave estable del dato, p. ej. `pokemon:firered:raichu:arrival`.
             */
            fact_key: string;
            /** @description `mechanic` (mecánica del juego), `key_battle` (equipo de un combate clave), `exists` (la forma se puede tener en el juego) o `arrival` (puede llegar y evolucionar antes de completarlo). */
            kind: components["schemas"]["FactKind"];
            /**
             * Subject
             * @description La mecánica, el combate clave o la forma.
             */
            subject: string;
            /**
             * Name
             * @description Nombre en español de la mecánica, el entrenador o el Pokémon.
             */
            name: string;
            /** @description `inferred` (con propuesta) o `pending` (sin propuesta). */
            origin: components["schemas"]["LoadedOrigin"];
            /** @description Valor propuesto por la carga; nulo si está pendiente. Un booleano (mecánica, existencia o llegada) o, en un combate clave, la lista de Pokémon de su equipo en orden. */
            proposal: components["schemas"]["ReviewValue"] | null;
            /** @description `pending` si hay que confirmarlo antes de generar; `confirmed` si ya está. */
            status: components["schemas"]["ReviewStatus"];
            /** @description El valor confirmado; nulo si no lo está. */
            value: components["schemas"]["ReviewValue"] | null;
            /**
             * Confirmed At
             * @description Cuándo se confirmó; nulo si no lo está.
             */
            confirmed_at: string | null;
            /**
             * Outdated
             * @description Se confirmó, pero una carga posterior propone otro valor: hay que volver a confirmarlo.
             */
            outdated: boolean;
            /**
             * Source Url
             * @description En un combate clave, la revisión de la página de WikiDex de la que sale su equipo (ADR-0004); nula en los demás datos o si no se conoce.
             */
            source_url: string | null;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Game
             * @description Identificador del juego.
             */
            game: string;
            /**
             * Pending
             * @description Datos que faltan por confirmar; con 0 se puede generar.
             */
            pending: number;
            /**
             * Facts
             * @description Los datos inferidos o pendientes que intervienen en la generación: primero los del juego (mecánicas y, con RN-17 activa, combates clave) y después los de cada favorito en orden de la Pokédex Nacional, salvo los ya descartados con datos conocidos.
             */
            facts: components["schemas"]["ReviewFactOut"][];
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "pending" | "confirmed";
        ReviewValue: boolean | string[];
        /**
         * RuleKind
         * @enum {string}
         */
        RuleKind: "hard" | "presence" | "soft" | "mechanism";
        /** RuleOut */
        RuleOut: {
            /**
             * Rule Id
             * @description Identificador del DDF, p. ej. `RN-17`.
             */
            rule_id: string;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /**
             * Description
             * @description Qué hace la regla, en una frase.
             */
            description: string;
            /** @description `hard` (filtro), `presence` (obliga a incluir un tipo de miembro), `soft` (puntúa) o `mechanism` (cómo funciona el motor). */
            kind: components["schemas"]["RuleKind"];
            /**
             * Configurable
             * @description Si el usuario la puede activar y desactivar.
             */
            configurable: boolean;
            /**
             * Enabled
             * @description Si está activa.
             */
            enabled: boolean;
            /**
             * Weight
             * @description Peso actual, solo en las reglas blandas.
             */
            weight: number | null;
            /**
             * Default Weight
             * @description Peso por defecto, solo en las blandas.
             */
            default_weight: number | null;
        };
        /**
         * RulePatch
         * @description What to change; at least one of the two.
         */
        RulePatch: {
            /**
             * Enabled
             * @description Activarla (`true`) o desactivarla (`false`); solo en las configurables.
             */
            enabled?: boolean | null;
            /**
             * Weight
             * @description Peso nuevo, de 0 a 10; solo en las blandas.
             */
            weight?: number | null;
        };
        /**
         * RuleScoreOut
         * @description What one active soft rule adds to the team's score (RF-09).
         */
        RuleScoreOut: {
            /**
             * Rule Id
             * @description Regla blanda, p. ej. `RN-17`.
             */
            rule_id: string;
            /**
             * Name
             * @description Nombre de la regla.
             */
            name: string;
            /**
             * Weight
             * @description Peso de la regla, de 0 a 10.
             */
            weight: number;
            /**
             * Score
             * @description Puntuación de la regla en el equipo, en porcentaje (0 a 100).
             */
            score: number;
            /**
             * Contribution
             * @description Lo que aporta al total (peso · puntuación), redondeado de forma que las aportaciones sumen la puntuación del equipo.
             */
            contribution: number;
            /**
             * Penalized
             * @description Miembros que cuentan en contra.
             */
            penalized: string[];
        };
        /** SpeciesRefOut */
        SpeciesRefOut: {
            /**
             * Species
             * @description Identificador de la especie.
             */
            species: string;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
        };
        /** SuggestionOut */
        SuggestionOut: {
            /** @description El Pokémon sugerido, con sus tipos en el juego. */
            pokemon: components["schemas"]["PokemonOut"];
            /**
             * Gain
             * @description Lo que aportaría a la puntuación del equipo, redondeado.
             */
            gain: number;
            /**
             * Verified
             * @description Falso si alguno de sus datos está sin confirmar (CA-31).
             */
            verified: boolean;
        };
        /** TeamCheckIn */
        TeamCheckIn: {
            /**
             * Members
             * @description Las formas del equipo elegido, de 1 a 6, sin repetir: favoritos o sugerencias del resultado.
             */
            members: string[];
        };
        /** TeamCheckOut */
        TeamCheckOut: {
            /**
             * Valid
             * @description Si el equipo cumple las reglas activas.
             */
            valid: boolean;
            /**
             * Problems
             * @description Por cada regla que no se cumple: primero los filtros por miembro, después los pares incompatibles y por último las reglas de presencia.
             */
            problems: components["schemas"]["TeamProblemOut"][];
            /**
             * Unverified
             * @description Miembros con datos sin confirmar (CA-31). No es un problema.
             */
            unverified: string[];
        };
        /** TeamOut */
        TeamOut: {
            /**
             * Members
             * @description Los miembros, en orden de la Pokédex Nacional.
             */
            members: string[];
            /**
             * Score
             * @description Puntuación del equipo, redondeada.
             */
            score: number;
            /**
             * Dual Type Members
             * @description Miembros con dos tipos, para desempatar (RN-19).
             */
            dual_type_members: number;
            /**
             * Breakdown
             * @description Las reglas blandas activas, en orden del catálogo.
             */
            breakdown: components["schemas"]["RuleScoreOut"][];
            /**
             * Open Slots
             * @description Huecos con sus sugerencias, si el equipo tiene menos de 6 (RN-08).
             */
            open_slots: components["schemas"]["OpenSlotsOut"][];
        };
        /** TeamProblemOut */
        TeamProblemOut: {
            /**
             * Rule Id
             * @description La regla que no se cumple.
             */
            rule_id: string;
            /**
             * Members
             * @description Los miembros afectados: uno (un filtro), dos (incompatibles) o ninguno (una regla de presencia que el equipo no cumple).
             */
            members: string[];
            /**
             * Detail
             * @description Explicación en español.
             */
            detail: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WayOut
         * @description A way of obtaining it from the encounters of a game (RN-26).
         */
        WayOut: {
            /** @description `gift`, `npc_trade`, `fossil`, `static`, `wild`, `swarm` (salvaje en enjambre), `roaming`, `starter_gift` (depende del inicial) o `event` (RN-26, CA-82 a CA-87). */
            kind: components["schemas"]["EncounterKind"];
            /**
             * Location
             * @description Identificador del lugar.
             */
            location: string;
            /**
             * Location Name
             * @description Nombre del lugar en español; en inglés si no se conoce.
             */
            location_name: string;
            /**
             * Area
             * @description Zona del lugar (`b1f`); nula si solo tiene una.
             */
            area: string | null;
            /**
             * Method
             * @description Método de PokeAPI (`walk`, `surf`, `gift`…).
             */
            method: string;
            /**
             * Rarity
             * @description Probabilidad, en %, de encontrarlo en esa zona con ese método; con `times`, la mayor de esos momentos (CA-81).
             */
            rarity: number;
            /**
             * Times
             * @description Momentos del día (`morning`, `day`, `night`) en que tiene esa probabilidad; vacío si no depende de la hora (CA-81).
             */
            times: string[];
            /**
             * Choice
             * @description La elección de la que depende: `starter-<especie>` (el inicial elegido, CA-80, CA-87) o `tv-option-<color>` (la televisión de Esmeralda, CA-85).
             */
            choice: string | null;
            /**
             * Item
             * @description El fósil que se revive o el objeto de evento con el que se llega al lugar (CA-82).
             */
            item: string | null;
            /**
             * Conditions
             * @description El resto de condiciones de PokeAPI, para mostrarlas con la forma (`coins-9999`, `trade-abra`, `weekday-friday`…; CA-83, CA-85).
             */
            conditions: string[];
            /**
             * Alternatives
             * @description Los demás Pokémon de un regalo en el que se elige uno (CA-87).
             */
            alternatives: components["schemas"]["SpeciesRefOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_pokemon_api_pokemon_get: {
        parameters: {
            query?: {
                /** @description Parte del nombre o del identificador, sin distinguir mayúsculas ni tildes; los guiones del identificador cuentan como espacios (`mr mime`). */
                q?: string | null;
                /** @description Un tipo actual, p. ej. `fire`. */
                type?: string | null;
                /** @description Solo favoritos (`true`) o solo los que no lo son (`false`). */
                favorite?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pokemon_detail_api_pokemon__pokemon__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la forma, p. ej. `vulpix-alola` (RN-05). */
                pokemon: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokemonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pokemon_image_api_pokemon__pokemon__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la forma, p. ej. `vulpix-alola` (RN-05). */
                pokemon: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La imagen, en PNG. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pokemon_artwork_api_pokemon__pokemon__artwork_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la forma, p. ej. `vulpix-alola` (RN-05). */
                pokemon: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La ilustración, en PNG. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorites_api_favorites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesOut"];
                };
            };
        };
    };
    add_favorite_api_favorites__pokemon__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la forma, p. ej. `vulpix-alola` (RN-05). */
                pokemon: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favorite_api_favorites__pokemon__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la forma, p. ej. `vulpix-alola` (RN-05). */
                pokemon: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    update_rule_api_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la regla, p. ej. `RN-07`. */
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_api_games_get: {
        parameters: {
            query?: {
                /** @description Todos los juegos cargados, también los que no son juego objetivo, para el *Hall of Fame* (RF-12). */
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_cover_api_games__game__cover_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del juego, p. ej. `firered`. */
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La portada, en PNG. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_api_games__game__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del juego, p. ej. `firered`. */
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description El juego ya está registrado en el *Hall of Fame*: cada juego se completa una sola vez (CA-68). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedGameOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_games__game__review__fact_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Clave estable del dato, p. ej. `pokemon:firered:raichu:arrival`. */
                fact_key: string;
                /** @description Identificador del juego, p. ej. `firered`. */
                game: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewFactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_proposals_api_games__game__review_accept_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del juego, p. ej. `firered`. */
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description El juego ya está registrado en el *Hall of Fame*: cada juego se completa una sola vez (CA-68). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedGameOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_games__game__generations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del juego, p. ej. `firered`. */
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"];
                };
            };
            /** @description Quedan datos sin verificar que intervienen (RN-18), o el juego ya está registrado en el *Hall of Fame* (CA-68). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingDataOut"] | components["schemas"]["CompletedGameOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_team_api_games__game__team_checks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del juego, p. ej. `firered`. */
                game: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCheckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamCheckOut"];
                };
            };
            /** @description Quedan datos sin verificar que intervienen (RN-18), o el juego ya está registrado en el *Hall of Fame* (CA-68). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingDataOut"] | components["schemas"]["CompletedGameOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_api_hall_of_fame_get: {
        parameters: {
            query?: {
                /** @description Solo los registros de este juego. */
                game?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallOfFameEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_entry_api_hall_of_fame_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallOfFameEntryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallOfFameEntryOut"];
                };
            };
            /** @description El juego ya está registrado en el *Hall of Fame*: cada juego se completa una sola vez (CA-68). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedGameOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_entry_api_hall_of_fame__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del registro (`id`). */
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entry_api_hall_of_fame__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del registro (`id`). */
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallOfFamePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallOfFameEntryOut"];
                };
            };
            /** @description El juego ya está registrado en el *Hall of Fame*: cada juego se completa una sola vez (CA-68). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedGameOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pokedexes_api_pokedex_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokedexGameOut"][];
                };
            };
        };
    };
    get_pokedex_api_pokedex__game__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de un juego registrado en el *Hall of Fame*. */
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokedexOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_pokedex_api_pokedex__game__initial_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de un juego registrado en el *Hall of Fame*. */
                game: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitialListIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokedexOut"];
                };
            };
            /** @description La lista inicial ya está confirmada. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_objective_api_pokedex__game__objective_get: {
        parameters: {
            query?: {
                /** @description Especies saltadas de momento; no se guardan, y al volver a entrar el objetivo vuelve a ser el primero sin registrar (CA-77). */
                skipped?: string[] | null;
            };
            header?: never;
            path: {
                /** @description Identificador de un juego registrado en el *Hall of Fame*. */
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectiveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pokemon_api_pokedex__game__pokemon__species__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de un juego registrado en el *Hall of Fame*. */
                game: string;
                /** @description Identificador de la especie, p. ej. `pikachu` (no de la forma). */
                species: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokedexPokemonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_pokemon_api_pokedex__game__pokemon__species__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de un juego registrado en el *Hall of Fame*. */
                game: string;
                /** @description Identificador de la especie, p. ej. `pikachu` (no de la forma). */
                species: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PokedexMarkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokedexPokemonOut"];
                };
            };
            /** @description La lista inicial no está confirmada. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unmark_pokemon_api_pokedex__game__pokemon__species__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de un juego registrado en el *Hall of Fame*. */
                game: string;
                /** @description Identificador de la especie, p. ej. `pikachu` (no de la forma). */
                species: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La lista inicial no está confirmada. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
}
