/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/pokemon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista de Pokémon
         * @description Todas las formas cargadas, en orden de la Pokédex Nacional, con sus tipos actuales y si
         *     están en favoritos. Las formas regionales son entradas propias.
         */
        get: operations["list_pokemon_api_pokemon_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pokemon/{pokemon}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ficha de un Pokémon
         * @description Número, nombre, tipos actuales, línea evolutiva completa y el mecanismo de cada
         *     evolución. `404` si la forma no existe.
         */
        get: operations["pokemon_detail_api_pokemon__pokemon__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista de favoritos
         * @description Los favoritos, en orden de la Pokédex Nacional, y cuántos hay.
         */
        get: operations["list_favorites_api_favorites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/{pokemon}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Añadir un favorito
         * @description Añade la forma `pokemon`, la evolución hasta la que se quiere llegar (RN-09). Si ya era
         *     favorito, no cambia nada. `404` si la forma no existe en los datos cargados.
         */
        put: operations["add_favorite_api_favorites__pokemon__put"];
        post?: never;
        /**
         * Quitar un favorito
         * @description Quita `pokemon` de favoritos. `404` si no estaba.
         */
        delete: operations["remove_favorite_api_favorites__pokemon__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo de reglas
         * @description Las 20 reglas del catálogo, en orden, con su tipo, si son configurables, si están
         *     activas y su peso.
         */
        get: operations["list_rules_api_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Activar, desactivar o cambiar el peso de una regla
         * @description Cambia `enabled`, `weight` (de 0 a 10, solo en las blandas) o los dos. `404` si la regla
         *     no existe; `409` si no es configurable o no es blanda y se le da peso.
         */
        patch: operations["update_rule_api_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Juegos objetivo
         * @description Los juegos que se pueden elegir como objetivo, en orden de lanzamiento: los de la saga
         *     principal con datos cargados que permiten la crianza (RF-05). Con `all=true`, todos los
         *     juegos cargados; `target` dice cuáles pueden ser juego objetivo.
         */
        get: operations["list_games_api_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Datos sin verificar del juego
         * @description Los datos inferidos o pendientes que intervienen en la generación con los favoritos y
         *     las reglas actuales, con su propuesta y su estado (RN-18). Con `pending` a 0 se puede
         *     generar. `404` si el juego no es juego objetivo.
         */
        get: operations["get_review_api_games__game__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game}/review/{fact_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Confirmar o corregir un dato
         * @description Confirma el dato con el valor propuesto o con uno corregido: un booleano o, en un
         *     combate clave, la lista de Pokémon de su equipo. `404` si el dato no existe en el juego;
         *     `409` si se cargó sin ambigüedad (automático); `422` si el valor no es del tipo del dato o
         *     el equipo incluye Pokémon que no existen en la generación del juego.
         */
        put: operations["confirm_api_games__game__review__fact_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game}/review/accept-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aceptar todas las propuestas
         * @description Confirma de una vez todas las propuestas inferidas que intervienen y aún no están
         *     confirmadas. Los datos pendientes, sin propuesta, se confirman uno a uno. Devuelve la
         *     revisión actualizada.
         */
        post: operations["accept_proposals_api_games__game__review_accept_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game}/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generar equipos
         * @description Genera los equipos con los favoritos, las reglas y las confirmaciones actuales. No se
         *     guarda: es un cálculo. `409` con los datos pendientes si queda alguno sin confirmar; `404`
         *     si el juego no es juego objetivo.
         */
        post: operations["generate_api_games__game__generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game}/team-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Comprobar un equipo elegido
         * @description Comprueba el equipo elegido en el resultado (favoritos y sugerencias) con las reglas
         *     activas: que cada miembro pase los filtros (RN-03, RN-11, RN-16), que no haya dos
         *     incompatibles (RN-07, RN-12, RN-14) y que se cumplan las reglas de presencia (RN-13,
         *     RN-14). No se guarda. `409` si quedan datos sin confirmar, como al generar; `422` si un
         *     miembro se repite o no existe en la generación del juego; `404` si el juego no es juego
         *     objetivo.
         */
        post: operations["check_team_api_games__game__team_checks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hall-of-fame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recorrido
         * @description Los registros en el orden del recorrido: por fecha y, a igualdad, por orden de registro.
         *     `last` marca el último juego completado. Con `game`, solo los de ese juego.
         */
        get: operations["list_entries_api_hall_of_fame_get"];
        put?: never;
        /**
         * Registrar un equipo
         * @description Registra el equipo con el que se completó un juego. Guarda los tipos que tenía cada
         *     miembro en ese juego. `422` si el juego o algún Pokémon no existen en los datos cargados
         *     (o en la generación del juego).
         */
        post: operations["add_entry_api_hall_of_fame_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hall-of-fame/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eliminar un registro
         * @description Elimina el registro y su equipo. `404` si no existe.
         */
        delete: operations["remove_entry_api_hall_of_fame__entry_id__delete"];
        options?: never;
        head?: never;
        /**
         * Corregir un registro
         * @description Cambia el juego, la fecha, las notas o el equipo. Si cambia el juego o el equipo, se
         *     vuelven a copiar los tipos. `404` si el registro no existe; `422` como al registrarlo.
         */
        patch: operations["update_entry_api_hall_of_fame__entry_id__patch"];
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versión de la aplicación y de los datos
         * @description Versión de la aplicación y de la carga de datos con la que trabaja (commit de PokeAPI,
         *     fecha y juegos). `503` si todavía no se han cargado los datos o hay que repetir la carga.
         */
        get: operations["get_meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CatalogOut */
        CatalogOut: {
            /**
             * Total
             * @description Pokémon que cumplen los filtros.
             */
            total: number;
            /**
             * Pokemon
             * @description En orden de la Pokédex Nacional.
             */
            pokemon: components["schemas"]["CatalogPokemonOut"][];
        };
        /** CatalogPokemonOut */
        CatalogPokemonOut: {
            /**
             * Pokemon
             * @description Identificador de la forma, p. ej. `vulpix-alola`.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español; el de una forma regional la identifica.
             */
            name: string;
            /**
             * Dex Number
             * @description Número de la Pokédex Nacional.
             */
            dex_number: number;
            /**
             * Types
             * @description Tipos actuales (de la última generación cargada).
             */
            types: string[];
            /**
             * Region
             * @description Región de una forma regional (`alola`, `galar`…).
             */
            region: string | null;
            /**
             * Favorite
             * @description Si está en favoritos.
             */
            favorite: boolean;
        };
        ConditionValue: string | number | boolean;
        /** ConfirmationIn */
        ConfirmationIn: {
            /** @description El valor propuesto o corregido. Un booleano (mecánica, existencia o llegada) o, en un combate clave, la lista de Pokémon de su equipo en orden. */
            value: components["schemas"]["ReviewValue"];
        };
        /** ConfirmedFactOut */
        ConfirmedFactOut: {
            /** Fact Key */
            fact_key: string;
            kind: components["schemas"]["FactKind"];
            /**
             * Name
             * @description Nombre en español de la mecánica, el entrenador o el Pokémon.
             */
            name: string;
            value: components["schemas"]["ReviewValue"];
        };
        /**
         * DataVersion
         * @description The load that built reference.sqlite.
         */
        DataVersion: {
            /**
             * Pokeapi Commit
             * @description Commit del volcado de PokeAPI usado.
             */
            pokeapi_commit: string | null;
            /**
             * Ingested At
             * Format: date-time
             * @description Cuándo terminó la carga.
             */
            ingested_at: string;
            /**
             * Games
             * @description Juegos cargados.
             */
            games: string[];
        };
        /** DiscardOut */
        DiscardOut: {
            /** Pokemon */
            pokemon: string;
            /** Name */
            name: string;
            /** Rule Id */
            rule_id: string;
            /** @description `generation`, `game` o `arrival` (RN-03), `breeding` (RN-11) o `journey` (RN-16). */
            reason: components["schemas"]["DiscardReason"];
            /**
             * Detail
             * @description Explicación en español.
             */
            detail: string;
            /**
             * Fact Key
             * @description El dato confirmado por el usuario que decidió el descarte, si lo hay.
             */
            fact_key: string | null;
        };
        /**
         * DiscardReason
         * @enum {string}
         */
        DiscardReason: "generation" | "game" | "arrival" | "breeding" | "journey";
        /** EvolutionMethodOut */
        EvolutionMethodOut: {
            /**
             * Trigger
             * @description Disparador de PokeAPI: `level-up`, `use-item`, `trade`, `shed`…
             */
            trigger: string;
            /**
             * Conditions
             * @description Condiciones de PokeAPI, p. ej. `{"minimum_level": 16}` o `{"trigger_item": "thunder-stone"}`.
             */
            conditions: {
                [key: string]: components["schemas"]["ConditionValue"];
            };
        };
        /** EvolutionOut */
        EvolutionOut: {
            /** From Pokemon */
            from_pokemon: string;
            /** To Pokemon */
            to_pokemon: string;
            /**
             * Version Group
             * @description Grupo de versiones más reciente con datos de esta evolución.
             */
            version_group: string;
            /**
             * Methods
             * @description Formas de evolucionar; varias si hay métodos alternativos.
             */
            methods: components["schemas"]["EvolutionMethodOut"][];
        };
        /**
         * FactKind
         * @enum {string}
         */
        FactKind: "mechanic" | "key_battle" | "exists" | "arrival";
        /** FavoriteOut */
        FavoriteOut: {
            /**
             * Pokemon
             * @description Identificador de la forma, p. ej. `vulpix-alola`.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /**
             * Dex Number
             * @description Número de la Pokédex Nacional.
             */
            dex_number: number;
            /**
             * Types
             * @description Tipos actuales (de la última generación cargada).
             */
            types: string[];
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /** FavoritesOut */
        FavoritesOut: {
            /**
             * Total
             * @description Número de favoritos.
             */
            total: number;
            /**
             * Favorites
             * @description En orden de la Pokédex Nacional.
             */
            favorites: components["schemas"]["FavoriteOut"][];
        };
        /** GameOut */
        GameOut: {
            /**
             * Game
             * @description Identificador del juego, p. ej. `firered`.
             */
            game: string;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /** Generation */
            generation: number;
            /**
             * Version Group
             * @description Grupo de versiones, p. ej. `firered-leafgreen`.
             */
            version_group: string;
            /**
             * Target
             * @description Si se puede elegir como juego objetivo (RF-05).
             */
            target: boolean;
        };
        /** GenerationOut */
        GenerationOut: {
            /** Game */
            game: string;
            /** @description `complete` si hay equipos de 6 favoritos; si no, `incomplete` (RN-08). */
            status: components["schemas"]["GenerationStatus"];
            /** @description Si es incompleto: `reserved_slot` (una regla de presencia necesita un Pokémon que no es favorito), `not_enough_candidates` (menos de 6 válidos) o `no_valid_team` (no hay 6 que cumplan juntos las reglas). */
            incomplete_reason: components["schemas"]["IncompleteReason"] | null;
            /**
             * Score
             * @description Puntuación de los equipos recomendados, redondeada.
             */
            score: number;
            /**
             * Groups
             * @description Los equipos empatados en cabeza, ya desempatados con RN-19, agrupados.
             */
            groups: components["schemas"]["GroupOut"][];
            /**
             * Discards
             * @description Favoritos descartados, en orden de la Pokédex Nacional (RF-10).
             */
            discards: components["schemas"]["DiscardOut"][];
            /**
             * Presence
             * @description Las reglas de presencia activas.
             */
            presence: components["schemas"]["PresenceOut"][];
            /**
             * Confirmed Facts
             * @description Datos confirmados por el usuario que intervienen en la generación (RF-09).
             */
            confirmed_facts: components["schemas"]["ConfirmedFactOut"][];
            /** @description La carga de datos usada. */
            data_version: components["schemas"]["DataVersion"] | null;
        };
        /**
         * GenerationStatus
         * @enum {string}
         */
        GenerationStatus: "complete" | "incomplete";
        /**
         * GroupOut
         * @description Tied teams that only differ in interchangeable members (CA-33).
         */
        GroupOut: {
            /**
             * Positions
             * @description Por cada posición, los Pokémon que la pueden ocupar, todos con los mismos tipos. Cada combinación es uno de los equipos del grupo.
             */
            positions: components["schemas"]["PokemonOut"][][];
            /** Teams */
            teams: components["schemas"]["TeamOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HallOfFameEntryIn */
        HallOfFameEntryIn: {
            /**
             * Game
             * @description Juego completado: cualquiera de los cargados.
             */
            game: string;
            /**
             * Completed On
             * Format: date
             * @description Cuándo se completó.
             */
            completed_on: string;
            /** Notes */
            notes?: string | null;
            /**
             * Members
             * @description Las formas del equipo, de 1 a 6, en orden (`vulpix-alola` para Vulpix de Alola). Puede repetirse una forma.
             */
            members: string[];
        };
        /** HallOfFameEntryOut */
        HallOfFameEntryOut: {
            /** Id */
            id: number;
            /**
             * Game
             * @description Identificador del juego completado.
             */
            game: string;
            /**
             * Game Name
             * @description Nombre en español del juego.
             */
            game_name: string;
            /**
             * Generation
             * @description Generación del juego (la de su lanzamiento); nula si ya no está cargado.
             */
            generation: number | null;
            /**
             * Completed On
             * Format: date
             */
            completed_on: string;
            /** Notes */
            notes: string | null;
            /**
             * Order
             * @description Posición en el recorrido: por fecha y, a igualdad, por orden de registro.
             */
            order: number;
            /**
             * Last
             * @description Si es el último juego completado del recorrido.
             */
            last: boolean;
            /** Members */
            members: components["schemas"]["HallOfFameMemberOut"][];
        };
        /** HallOfFameMemberOut */
        HallOfFameMemberOut: {
            /**
             * Position
             * @description Posición en el equipo, de 1 a 6.
             */
            position: number;
            /**
             * Pokemon
             * @description Identificador de la forma.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /**
             * Types
             * @description Tipos que tenía en ese juego, copiados al registrarlo.
             */
            types: string[];
        };
        /**
         * HallOfFamePatch
         * @description What to change; at least one field. ``notes: null`` removes the notes.
         */
        HallOfFamePatch: {
            /** Game */
            game?: string | null;
            /** Completed On */
            completed_on?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Members
             * @description Las formas del equipo, de 1 a 6, en orden (`vulpix-alola` para Vulpix de Alola). Puede repetirse una forma.
             */
            members?: string[] | null;
        };
        /**
         * IncompleteReason
         * @description Why there is no team of 6 favourites (RN-08, RF-10).
         * @enum {string}
         */
        IncompleteReason: "reserved_slot" | "not_enough_candidates" | "no_valid_team";
        /** LineMemberOut */
        LineMemberOut: {
            /**
             * Pokemon
             * @description Identificador de la forma, p. ej. `vulpix-alola`.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español; el de una forma regional la identifica.
             */
            name: string;
            /**
             * Dex Number
             * @description Número de la Pokédex Nacional.
             */
            dex_number: number;
            /**
             * Types
             * @description Tipos actuales (de la última generación cargada).
             */
            types: string[];
            /**
             * Region
             * @description Región de una forma regional (`alola`, `galar`…).
             */
            region: string | null;
            /**
             * Favorite
             * @description Si está en favoritos.
             */
            favorite: boolean;
            /**
             * Stage
             * @description Etapa en la línea: 1 para la primera.
             */
            stage: number;
        };
        /**
         * LoadedOrigin
         * @description Origin of a reviewable value in the load (RN-18); automatic ones are not reviewed.
         * @enum {string}
         */
        LoadedOrigin: "inferred" | "pending";
        /** Meta */
        Meta: {
            /**
             * App Version
             * @description Versión de la aplicación.
             */
            app_version: string;
            /** @description La carga de los datos; nula si no hay registro. */
            data: components["schemas"]["DataVersion"] | null;
        };
        /** OpenSlotsOut */
        OpenSlotsOut: {
            /**
             * Count
             * @description Cuántos huecos son.
             */
            count: number;
            /**
             * Rule Id
             * @description La regla de presencia que reserva el hueco; nula si son huecos libres.
             */
            rule_id: string | null;
            /**
             * Suggestions
             * @description Todas las que encajan, de mejor a peor (CA-50). Con varios huecos libres, cada una encaja con el equipo, pero no necesariamente con las demás.
             */
            suggestions: components["schemas"]["SuggestionOut"][];
        };
        /** PendingDataDetail */
        PendingDataDetail: {
            /** Message */
            message: string;
            /**
             * Pending
             * @description Los datos que faltan por confirmar.
             */
            pending: components["schemas"]["ReviewFactOut"][];
        };
        /**
         * PendingDataOut
         * @description Body of the 409 when some data that takes part is still unverified (RN-18).
         */
        PendingDataOut: {
            detail: components["schemas"]["PendingDataDetail"];
        };
        /** PokemonDetailOut */
        PokemonDetailOut: {
            /**
             * Pokemon
             * @description Identificador de la forma, p. ej. `vulpix-alola`.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español; el de una forma regional la identifica.
             */
            name: string;
            /**
             * Dex Number
             * @description Número de la Pokédex Nacional.
             */
            dex_number: number;
            /**
             * Types
             * @description Tipos actuales (de la última generación cargada).
             */
            types: string[];
            /**
             * Region
             * @description Región de una forma regional (`alola`, `galar`…).
             */
            region: string | null;
            /**
             * Favorite
             * @description Si está en favoritos.
             */
            favorite: boolean;
            /**
             * Generation
             * @description Generación en que apareció la especie.
             */
            generation: number;
            /** Species */
            species: string;
            /** Is Legendary */
            is_legendary: boolean;
            /** Is Mythical */
            is_mythical: boolean;
            /**
             * Line
             * @description La línea evolutiva completa, con todas sus formas, por etapa y número.
             */
            line: components["schemas"]["LineMemberOut"][];
            /**
             * Evolutions
             * @description Cada evolución de la línea y su mecanismo.
             */
            evolutions: components["schemas"]["EvolutionOut"][];
        };
        /** PokemonOut */
        PokemonOut: {
            /**
             * Pokemon
             * @description Identificador de la forma.
             */
            pokemon: string;
            /**
             * Name
             * @description Nombre en español.
             */
            name: string;
            /**
             * Dex Number
             * @description Número de la Pokédex Nacional.
             */
            dex_number: number;
            /**
             * Types
             * @description Tipos en el juego objetivo, el primario primero.
             */
            types: string[];
        };
        /** PresenceOut */
        PresenceOut: {
            /** Rule Id */
            rule_id: string;
            /**
             * Level
             * @description Nivel de la regla en el DDF que se aplica.
             */
            level: number;
            /** @description `candidates` (el equipo incluye una de `options`), `reserved` (se reserva un hueco para una de `options`, que no son favoritos) o `unmet` (no se puede cumplir). */
            status: components["schemas"]["PresenceStatus"];
            /** Options */
            options: string[];
            /** Detail */
            detail: string;
        };
        /**
         * PresenceStatus
         * @enum {string}
         */
        PresenceStatus: "candidates" | "reserved" | "unmet";
        /** ReviewFactOut */
        ReviewFactOut: {
            /**
             * Fact Key
             * @description Clave estable del dato, p. ej. `pokemon:firered:raichu:arrival`.
             */
            fact_key: string;
            /** @description `mechanic` (mecánica del juego), `key_battle` (equipo de un combate clave), `exists` (la forma se puede tener en el juego) o `arrival` (puede llegar y evolucionar antes de completarlo). */
            kind: components["schemas"]["FactKind"];
            /**
             * Subject
             * @description La mecánica, el combate clave o la forma.
             */
            subject: string;
            /**
             * Name
             * @description Nombre en español de la mecánica, el entrenador o el Pokémon.
             */
            name: string;
            /** @description `inferred` (con propuesta) o `pending` (sin propuesta). */
            origin: components["schemas"]["LoadedOrigin"];
            /** @description Valor propuesto por la carga; nulo si está pendiente. Un booleano (mecánica, existencia o llegada) o, en un combate clave, la lista de Pokémon de su equipo en orden. */
            proposal: components["schemas"]["ReviewValue"] | null;
            /** @description `pending` si hay que confirmarlo antes de generar; `confirmed` si ya está. */
            status: components["schemas"]["ReviewStatus"];
            /** @description El valor confirmado; nulo si no lo está. */
            value: components["schemas"]["ReviewValue"] | null;
            /**
             * Confirmed At
             * @description Cuándo se confirmó; nulo si no lo está.
             */
            confirmed_at: string | null;
            /**
             * Outdated
             * @description Se confirmó, pero una carga posterior propone otro valor: hay que volver a confirmarlo.
             */
            outdated: boolean;
        };
        /** ReviewOut */
        ReviewOut: {
            /** Game */
            game: string;
            /**
             * Pending
             * @description Datos que faltan por confirmar; con 0 se puede generar.
             */
            pending: number;
            /**
             * Facts
             * @description Los datos inferidos o pendientes que intervienen en la generación: primero los del juego (mecánicas y, con RN-17 activa, combates clave) y después los de cada favorito en orden de la Pokédex Nacional, salvo los ya descartados con datos conocidos.
             */
            facts: components["schemas"]["ReviewFactOut"][];
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "pending" | "confirmed";
        ReviewValue: boolean | string[];
        /**
         * RuleKind
         * @enum {string}
         */
        RuleKind: "hard" | "presence" | "soft" | "mechanism";
        /** RuleOut */
        RuleOut: {
            /**
             * Rule Id
             * @description Identificador del DDF, p. ej. `RN-17`.
             */
            rule_id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @description Qué hace la regla, en una frase.
             */
            description: string;
            /** @description `hard` (filtro), `presence` (obliga a incluir un tipo de miembro), `soft` (puntúa) o `mechanism` (cómo funciona el motor). */
            kind: components["schemas"]["RuleKind"];
            /**
             * Configurable
             * @description Si el usuario la puede activar y desactivar.
             */
            configurable: boolean;
            /** Enabled */
            enabled: boolean;
            /**
             * Weight
             * @description Peso actual, solo en las reglas blandas.
             */
            weight: number | null;
            /**
             * Default Weight
             * @description Peso por defecto, solo en las blandas.
             */
            default_weight: number | null;
        };
        /**
         * RulePatch
         * @description What to change; at least one of the two.
         */
        RulePatch: {
            /** Enabled */
            enabled?: boolean | null;
            /** Weight */
            weight?: number | null;
        };
        /**
         * RuleScoreOut
         * @description What one active soft rule adds to the team's score (RF-09).
         */
        RuleScoreOut: {
            /** Rule Id */
            rule_id: string;
            /** Name */
            name: string;
            /**
             * Weight
             * @description Peso de la regla, de 0 a 10.
             */
            weight: number;
            /**
             * Score
             * @description Puntuación de la regla en el equipo, en porcentaje (0 a 100).
             */
            score: number;
            /**
             * Contribution
             * @description Lo que aporta al total (peso · puntuación), redondeado de forma que las aportaciones sumen la puntuación del equipo.
             */
            contribution: number;
            /**
             * Penalized
             * @description Miembros que cuentan en contra.
             */
            penalized: string[];
        };
        /** SuggestionOut */
        SuggestionOut: {
            pokemon: components["schemas"]["PokemonOut"];
            /**
             * Gain
             * @description Lo que aportaría a la puntuación del equipo, redondeado.
             */
            gain: number;
            /**
             * Verified
             * @description Falso si alguno de sus datos está sin confirmar (CA-31).
             */
            verified: boolean;
        };
        /** TeamCheckIn */
        TeamCheckIn: {
            /**
             * Members
             * @description Las formas del equipo elegido, de 1 a 6, sin repetir: favoritos o sugerencias del resultado.
             */
            members: string[];
        };
        /** TeamCheckOut */
        TeamCheckOut: {
            /**
             * Valid
             * @description Si el equipo cumple las reglas activas.
             */
            valid: boolean;
            /**
             * Problems
             * @description Por cada regla que no se cumple: primero los filtros por miembro, después los pares incompatibles y por último las reglas de presencia.
             */
            problems: components["schemas"]["TeamProblemOut"][];
            /**
             * Unverified
             * @description Miembros con datos sin confirmar (CA-31). No es un problema.
             */
            unverified: string[];
        };
        /** TeamOut */
        TeamOut: {
            /**
             * Members
             * @description Los miembros, en orden de la Pokédex Nacional.
             */
            members: string[];
            /**
             * Score
             * @description Puntuación del equipo, redondeada.
             */
            score: number;
            /**
             * Dual Type Members
             * @description Miembros con dos tipos, para desempatar (RN-19).
             */
            dual_type_members: number;
            /**
             * Breakdown
             * @description Las reglas blandas activas, en orden del catálogo.
             */
            breakdown: components["schemas"]["RuleScoreOut"][];
            /**
             * Open Slots
             * @description Huecos con sus sugerencias, si el equipo tiene menos de 6 (RN-08).
             */
            open_slots: components["schemas"]["OpenSlotsOut"][];
        };
        /** TeamProblemOut */
        TeamProblemOut: {
            /**
             * Rule Id
             * @description La regla que no se cumple.
             */
            rule_id: string;
            /**
             * Members
             * @description Los miembros afectados: uno (un filtro), dos (incompatibles) o ninguno (una regla de presencia que el equipo no cumple).
             */
            members: string[];
            /**
             * Detail
             * @description Explicación en español.
             */
            detail: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_pokemon_api_pokemon_get: {
        parameters: {
            query?: {
                /** @description Parte del nombre o del identificador; sin distinguir mayúsculas ni tildes. */
                q?: string | null;
                /** @description Un tipo actual, p. ej. `fire`. */
                type?: string | null;
                /** @description Solo favoritos (`true`) o solo los que no lo son (`false`). */
                favorite?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pokemon_detail_api_pokemon__pokemon__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pokemon: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokemonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorites_api_favorites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesOut"];
                };
            };
        };
    };
    add_favorite_api_favorites__pokemon__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pokemon: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favorite_api_favorites__pokemon__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pokemon: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    update_rule_api_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_api_games_get: {
        parameters: {
            query?: {
                /** @description Todos los juegos cargados, también los que no son juego objetivo, para el *Hall of Fame* (RF-12). */
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_api_games__game__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_games__game__review__fact_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_key: string;
                game: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewFactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_proposals_api_games__game__review_accept_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_games__game__generations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"];
                };
            };
            /** @description Quedan datos sin verificar que intervienen (RN-18). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingDataOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_team_api_games__game__team_checks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCheckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamCheckOut"];
                };
            };
            /** @description Quedan datos sin verificar que intervienen (RN-18). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingDataOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_api_hall_of_fame_get: {
        parameters: {
            query?: {
                game?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallOfFameEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_entry_api_hall_of_fame_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallOfFameEntryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallOfFameEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_entry_api_hall_of_fame__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entry_api_hall_of_fame__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallOfFamePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallOfFameEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
}
