/** The catalogue of rules of the simulated API: the real one (core/rules/catalog.py). */
import type { Rule } from "../api/types";

export const CATALOG: Rule[] = [
  {
    rule_id: "RN-01",
    name: "El equipo tiene 6 Pokémon",
    description: "El equipo generado tiene exactamente 6 Pokémon.",
    kind: "hard",
    configurable: false,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-02",
    name: "Solo se eligen Pokémon favoritos",
    description: "Todos los miembros del equipo son favoritos.",
    kind: "hard",
    configurable: false,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-03",
    name: "Solo Pokémon de la generación y del juego objetivo",
    description:
      "Solo cuentan los Pokémon de la generación del juego objetivo que existen en él y pueden llegar y evolucionar antes de completarlo.",
    kind: "hard",
    configurable: false,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-04",
    name: "Equipos con mayor puntuación ponderada",
    description:
      "Se recomiendan los equipos con mayor puntuación: la suma de cada regla blanda activa por su peso.",
    kind: "mechanism",
    configurable: false,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-05",
    name: "Cada forma regional es un Pokémon distinto",
    description: "Cada forma regional es un Pokémon distinto.",
    kind: "hard",
    configurable: false,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-06",
    name: "Penalizar varias formas de la misma especie",
    description:
      "Puntúa en contra que el equipo tenga varias formas de la misma especie, como Vulpix y Vulpix de Alola.",
    kind: "soft",
    configurable: true,
    enabled: true,
    weight: 1,
    default_weight: 1,
  },
  {
    rule_id: "RN-07",
    name: "Sin líneas evolutivas repetidas",
    description: "El equipo no tiene dos miembros de la misma línea evolutiva.",
    kind: "hard",
    configurable: true,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-08",
    name: "Equipo incompleto y sugerencias",
    description:
      "Si no se llega a 6, se muestra el equipo incompleto con sugerencias para los huecos.",
    kind: "mechanism",
    configurable: false,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-09",
    name: "Cada favorito marca la evolución a la que llegar",
    description: "Cada favorito es la evolución hasta la que se quiere llegar.",
    kind: "hard",
    configurable: false,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-10",
    name: "Datos tal como son en el juego objetivo",
    description: "Los tipos, las eficacias y las evoluciones son los del juego objetivo.",
    kind: "mechanism",
    configurable: false,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-11",
    name: "Solo Pokémon que se pueden criar",
    description: "Solo se eligen Pokémon cuya línea se puede criar.",
    kind: "hard",
    configurable: true,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-12",
    name: "Sin tipos repetidos en el equipo",
    description: "Ningún tipo aparece en más de un miembro del equipo.",
    kind: "hard",
    configurable: true,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-13",
    name: "Dragonite o un Pokémon de tipo primario Dragón",
    description:
      "El equipo incluye a Dragonite o, si no es posible, un Pokémon de tipo primario Dragón.",
    kind: "presence",
    configurable: true,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-14",
    name: "Una evolución de Eevee, y solo una",
    description: "El equipo incluye una evolución de Eevee, y solo una.",
    kind: "presence",
    configurable: true,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-15",
    name: "Penalizar evoluciones tediosas",
    description:
      "Puntúa en contra los miembros que necesitan una evolución tediosa, como el intercambio.",
    kind: "soft",
    configurable: true,
    enabled: true,
    weight: 3,
    default_weight: 3,
  },
  {
    rule_id: "RN-16",
    name: "Excluir Pokémon ya usados en el recorrido",
    description: "Se excluyen los Pokémon ya usados en el recorrido del Hall of Fame.",
    kind: "hard",
    configurable: true,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-17",
    name: "Tipos eficaces frente a los combates clave",
    description:
      "Puntúa a favor que los tipos del equipo sean eficaces, en ataque y en defensa, frente a los combates clave del juego.",
    kind: "soft",
    configurable: true,
    enabled: true,
    weight: 10,
    default_weight: 10,
  },
  {
    rule_id: "RN-18",
    name: "Los datos sin verificar los confirma el usuario",
    description:
      "Los datos que no se han podido cargar con certeza los confirma el usuario antes de generar.",
    kind: "mechanism",
    configurable: false,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-19",
    name: "A igual puntuación, Pokémon con dos tipos",
    description: "A igual puntuación, se prefieren los equipos con más Pokémon de dos tipos.",
    kind: "mechanism",
    configurable: false,
    enabled: true,
    weight: null,
    default_weight: null,
  },
  {
    rule_id: "RN-20",
    name: "Penalizar las evoluciones aleatorias",
    description:
      "Puntúa en contra los miembros que necesitan una evolución aleatoria, como Wurmple.",
    kind: "soft",
    configurable: true,
    enabled: true,
    weight: 5,
    default_weight: 5,
  },
];
